### ISSUE TITLE
Hello  i want to change timer word in English  is it possible??

### ISSUE THREAD

**Issue by ghost** [HamidrezaAmz/MagicalExoPlayer#39]
Hello

i want to change timer word in English

is it possible??

**Comment by HamidrezaAmz** [comment]
Hi
Yes just update your [MagicalExoPlayer](https://github.com/HamidrezaAmz/MagicalExoPlayer) to the latest version.
If the problem is still the set your application locale to 'EN', Here is an example for you: [set locale programmatically](https://stackoverflow.com/questions/4985805/set-locale-programmatically)
